version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app  # Hot reload during development
      - ./logs:/app/logs  # Add this line to mount the logs directory